# Redirect with a 301
[[redirects]]
from = "/posts/*"
to = "https://dlibin.net/posts/:splat"
status = 301

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/postsMetaData.json"
    [headers.values]
    Access-Control-Allow-Origin = "*"
