# Redirect with a 301
[[redirects]]
from = "https://questsincode.com/*"
to = "https://dlibin.net/:splat"
status = 301
force = true

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/postsMetaData.json"
    [headers.values]
    Access-Control-Allow-Origin = "*"
